@startuml
actor Employee
participant "Sistem" as System
database "Database" as DB

title 1. Alur Menampilkan Daftar Jadwal

Employee -> System : 1. Membuka halaman pengelolaan jadwal
activate System
System -> DB : 2. Ambil semua data jadwal
activate DB
DB --> System : 3. Data jadwal
deactivate DB
System --> Employee : 4. Menampilkan halaman dengan daftar jadwal
deactivate System
@enduml