@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor "Member"
actor "Guest"
actor "Employee"
actor "Manager"
actor "Admin"

rectangle "Sistem Penyewaan Lapangan Olahraga" {
  usecase "Reset \nPassword" as uc1
  usecase "Registrasi" as uc2
  usecase "Kelola \nData Diri" as uc3
  usecase "Print \nTiket" as uc4
  usecase "Melakukan \nPembayaran" as uc5
  usecase "Menyewa \nLapangan" as uc6
  usecase "Batalkan \nPesanan" as uc7
  usecase "Rating dan Komentar" as uc8
  usecase "Melihat Riwayat \nTranksaksi" as uc9
  usecase "Melihat \nArena" as uc10
  usecase "Memilih Kategori \nLokasi" as uc11
  usecase "Memilih Kategori \nHarga" as uc12
  usecase "Memilih Kategori \nJenis Lapangan" as uc13
  usecase "Login" as uc14
  usecase "Menetukan \nKategori Arena" as uc15
  usecase "Mengelola \nArena" as uc16
  usecase "Mengelola \nTransaksi Sewa" as uc17
  usecase "List \nPenyewa" as uc18
  usecase "Mengelola \nPembayaran" as uc19
  usecase "Print Transaksi \nPembayaran" as uc20
  usecase "Mengelola \nRekening Bank" as uc21
  usecase "Mengelola \nMember" as uc22
  usecase "Mengelola \nTransaksi" as uc23
  usecase "Forum \nDiskusi" as uc24
}

' Guest associations
Guest ---- uc2
Guest ---- uc10
Guest ---- uc11
Guest ---- uc12
Guest ---- uc13

' Member/Penyewa associations
Member ---- uc1
Member ---- uc3
Member ---- uc4
Member ---- uc5
Member ---- uc6
Member ---- uc7
Member ---- uc8
Member ---- uc9
Member ---- uc10
Member ---- uc14
Member ---- uc24

' Employee/Pengelola associations
uc14 ---- Employee
uc15 ---- Employee
uc16 ---- Employee
uc17 ---- Employee
uc18 ---- Employee
uc19 ---- Employee
uc20 ---- Employee
uc21 ---- Employee

' Admin associations
uc14 ---- Admin
uc22 ---- Admin
uc23 ---- Admin
uc24 ---- Admin

' Use case relationships
uc14 <.. uc1 : <<include>>
uc14 <.. uc3 : <<include>>
uc14 <.. uc4 : <<include>>
uc14 <.. uc5 : <<include>>
uc14 <.. uc6 : <<include>>
uc14 <.. uc7 : <<include>>
uc14 <.. uc8 : <<include>>
uc14 <.. uc9 : <<include>>
uc14 <.. uc15 : <<include>>
uc14 <.. uc16 : <<include>>
uc14 <.. uc17 : <<include>>
uc14 <.. uc18 : <<include>>
uc14 <.. uc19 : <<include>>
uc14 <.. uc20 : <<include>>
uc14 <.. uc21 : <<include>>
uc14 <.. uc22 : <<include>>
uc14 <.. uc23 : <<include>>
uc14 <.. uc24 : <<include>>

uc10 <.. uc11 : <<extend>>
uc10 <.. uc12 : <<extend>>
uc10 <.. uc13 : <<extend>>

uc6 ..> uc5 : <<include>>
uc5 ..> uc4 : <<include>>
uc19 ..> uc20 : <<include>>

@enduml