@startuml
|Pengguna|
start
:Membuka halaman browse lapangan;
:Atur filter (opsional);

|Sistem|
:Tampilkan daftar lapangan;

|Pengguna|
:Pilih lapangan untuk detail;

|Sistem|
:Tampilkan detail lapangan, rating, & review;

|Pengguna|
if (Member?) then (Ya)
  if (Booking?) then (Ya)
    :Lanjut proses booking;
  else (Tidak)
    :Kembali ke daftar lapangan;
  endif
else (Bukan)
  :Lihat info saja;
endif
stop
@enduml