@startuml
|Member|
start
:Login ke sistem;
:Pilih lapangan, tanggal & waktu;

|Sistem|
if (Jadwal tersedia?) then (Ya)
  :Buat booking sementara & arahkan ke pembayaran;
  |Member|
  :Melakukan pembayaran;
  |Sistem|
  if (Pembayaran berhasil?) then (Ya)
    :Konfirmasi booking & update status;
    :Tampilkan konfirmasi booking;
  else (Tidak)
    :Batalkan booking & tampilkan pesan gagal bayar;
  endif
else (Tidak)
  :Tampilkan pesan jadwal tidak tersedia;
endif
stop
@enduml