@startuml
|Guest|
start
:Mengisi & submit formulir pendaftaran;

|Sistem|
if (Data valid & email belum terdaftar?) then (Ya)
  :Simpan akun baru & tampilkan pesan sukses;
else (Tidak)
  :Tampilkan pesan error registrasi;
endif
stop
@enduml