@startuml
actor Member
participant "Sistem" as System
database "Database" as DB

title 2. Alur Melakukan Pencarian Lapangan

Member -> System : 1. Memasukkan kriteria & mengirim permintaan pencarian
activate System
System -> DB : 2. Cari data lapangan sesuai kriteria (query)
activate DB
DB --> System : 3. Data hasil pencarian
deactivate DB

alt Hasil Ditemukan
    System --> Member : 4a. Menampilkan daftar lapangan hasil pencarian
else Hasil Tidak Ditemukan
    System --> Member : 4b. Menampilkan pesan "Lapangan tidak ditemukan"
end

deactivate System
@enduml