@startuml
actor Member
participant "Sistem" as System
database "Database" as DB

title 2. Alur Melihat Detail Lapangan

Member -> System : 1. Memilih satu lapangan dari daftar
activate System
System -> DB : 2. Ambil detail & jadwal lapangan spesifik
activate DB
DB --> System : 3. Mengirimkan data detail & jadwal
deactivate DB
System --> Member : 4. Menampilkan detail lengkap & jadwal yang tersedia
deactivate System
@enduml