@startuml
left to right direction
actor Guest
actor Member
actor Admin
actor Manager
actor Employee

rectangle "Sistem Booking Lapangan Olahraga" {
  Guest -- (Register)
  Guest -- (Login)
  Guest -- (Browse Lapangan)

  Member -- (Login)
  Member -- (Browse Lapangan)
  Member -- (Booking Lapangan)
  Member -- (Melakukan Pembayaran)
  Member -- (Melihat Riwayat Booking)
  Member -- (Memberikan Rating)

  Admin -- (Login)
  Admin -- (Kelola User)
  Admin -- (Kelola Lapangan)
  Admin -- (Kelola Jadwal)
  Admin -- (Kelola Pembayaran)
  Admin -- (Generate Laporan)

  Manager -- (Login)
  Manager -- (Kelola Jadwal)
  Manager -- (Kelola Booking)
  Manager -- (Generate Laporan)

  Employee -- (Login)
  Employee -- (Kelola Lapangan)
  Employee -- (Kelola Jadwal)
}

@enduml
