@startuml
actor User
participant "FieldTypePage/FilterPage" as UI
participant "FieldTypeController" as Controller
participant "FieldTypeService" as Service
participant "FieldType" as FieldTypeEntity

User -> UI : Buka halaman jenis lapangan
UI -> Controller : getFieldTypes()
Controller -> Service : fetchFieldTypes()
Service -> FieldTypeEntity : getAllFieldTypes()
FieldTypeEntity --> Service : fieldTypeList
Service -> Controller : fieldTypeList
Controller -> UI : fieldTypeList
UI -> User : tampilkan daftar jenis lapangan
@enduml
