@startuml
actor Admin
participant "Sistem" as System
database "Database" as DB

title Alur Menampilkan Daftar Jadwal

Admin -> System : 1. Membuka halaman jadwal
activate System

System -> DB : 2. Ambil data semua jadwal
activate DB
DB --> System : 3. Mengirimkan data jadwal
deactivate DB

System --> Admin : 4. Menampilkan halaman dengan daftar jadwal
deactivate System
@enduml